on:
  push:
    branches: main
  pull_request:
    branches: main

name: Test CDMConnector cdm_from_environment

jobs:
  CDMConnector:
    if: github.repository == 'darwin-eu-dev/AnalysisLibrary'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      
      - name: Cache Docker image layers
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-executionengine.azurecr.io/darwin-base:v0.1
            
      - name: pull docker image
        run: docker pull executionengine.azurecr.io/darwin-base:v0.1
      
      - name: run simple test
        run: |
          R -e 'df <- read.csv("https://raw.githubusercontent.com/OHDSI/PhenotypeLibrary/main/inst/Cohorts.csv"); print(dplyr::tibble(df))'
        
   
