on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: TestDatabaseConnector

jobs:
  Postgres-test:
    if: github.repository == 'darwin-eu-dev/AnalysisLibrary'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.1
      env:
        DBMS_TYPE: 'postgresql'
        DBMS_USERNAME:  ${{ secrets.POSTGRESQL_USER }}
        DBMS_SERVER:    ${{ secrets.POSTGRESQL_SERVER }}
        DBMS_PASSWORD:  ${{ secrets.POSTGRESQL_PASSWORD }}
        DBMS_NAME:      ${{ secrets.POSTGRESQL_DATABASE }}
        DBMS_CATALOG:   ${{ secrets.POSTGRESQL_WAREHOUSE }}
        CDM_SCHEMA:     ${{ secrets.POSTGRESQL_CDM_SCHEMA }}
        WRITE_SCHEMA: ${{ secrets.POSTGRESQL_SCRATCH_SCHEMA }}
        TESTTHAT_CPUS : 1

    name: Postgres test (DatabaseConnector)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: R -e 'source("./TestDatabaseConnector/main.R")'

  SqlServer-test:
    if: github.repository == 'darwin-eu-dev/AnalysisLibrary'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.1
      env:
        DBMS_TYPE: 'sql server'
        DBMS_USER:      ${{ secrets.SQL_SERVER_USER }}
        DBMS_SERVER:    ${{ secrets.SQL_SERVER_SERVER }}
        DBMS_PASSWORD:  ${{ secrets.SQL_SERVER_PASSWORD }}
        DB_NAME:        ${{ secrets.SQL_SERVER_DATABASE }}
        CDM_SCHEMA:     ${{ secrets.SQL_SERVER_CDM_SCHEMA }}
        SCRATCH_SCHEMA: ${{ secrets.SQL_SERVER_SCRATCH_SCHEMA }}
        TESTTHAT_CPUS : 1

    name: Sql Server test (DatabaseConnector)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: R -e 'source("./TestDatabaseConnector/main.R")'

